application:
    security:
        jwt:
            secret-key: 397A24432646294A404E635166546A576E5A7234753778214125442A472D4B6150645367556B58703273357638792F423F4528482B4D6251655468576D597133
            expiration: 86400000 # a day
            refresh-token:
              expiration: 604800000 # 7 days
logging:
    level:
        org.springframework:
            security: TRACE
            hibernate.SQL: DEBUG
            hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: auk.sw.solutions@gmail.com
        password: jskyiovmaucqsafa
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 21MB